### PR TITLE
Add stable build

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @gkoz

### CODE REVIEW

**Comment by gkoz** [comment]
I guess we should discuss our strategy with regard to various existing Rust branches.
BTW, one option I hadn't considered before could be tracking only stable and beta.

Keeping with the status quo would be changing beta to stable so we would be targeting 1.0-release and 1.2-nightly (there should've been 1.1-beta released yesterday and the nightly should've become 1.2 but that part may have been postponed for Monday or whatever).
Surely we won't abandon 1.0 today, as for 1.1 I'm not sure of its significance yet but whatever builds with 1.0 should be compatible with that as well.

**Comment by GuillaumeGomez** [comment]
Just keeping beta and stable ? Hum... I'm afraid that would take a look at travis would open issue to say "Is it working on the stable version ? I didn't see it building with the last stable version of rust on travis" or stuff like that. I was thinking about that when I created this PR. If you really don't see it as useful, then let's just close this issue.

**Comment by gkoz** [comment]
Beta and stable is just an idea.
Beta isn't too useful now because it was a surrogate for missing stable.
I'd leave just stable and nightly for now.

**Comment by GuillaumeGomez** [comment]
Okay, let's do that for now then. I merge. I'll do that for all other libraries as well.

**Comment by gkoz** [comment]
You'll probably want to do the same to appveyor.yml

**Comment by GuillaumeGomez** [comment]
Can you take at it then ? It'll be faster that way.

**Comment by gkoz** [comment]
Okay

**Comment by GuillaumeGomez** [comment]
Thanks !

**Pull request merged**
