### PR TITLE
Implement more new style signals

### PR DESCRIPTION
**Pull request by gkoz**
I'd appreciate someone taking the time to review the closure and callback signatures against [the GTK docs](https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget.signals). The compiler can't be of much help here and it's easy to make a mistake.
The `GtkWidget` signals are here, other widgets to follow.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
For this, I think we'll have to write new examples. Maybe adding new ones to the current ? I'll create an example repo to split out examples from gtk.

**Comment by gkoz** [comment]
@GuillaumeGomez can you elaborate on the examples issue? I'm also curious why you put an older version of examples into the new repo.

**Comment by GuillaumeGomez** [comment]
I just spitted out the existing gtk examples.

**Comment by gkoz** [comment]
You gtk repo might've not been up to date then. Compare
https://github.com/rust-gnome/gtk/blob/master/examples/src/gtktest.rs and https://github.com/rust-gnome/examples/blob/master/src/gtktest.rs

**Comment by GuillaumeGomez** [comment]
Weird... Wanna fix it or I do it ?

**Comment by gkoz** [comment]
You do it please =)

**Comment by GuillaumeGomez** [comment]
Ok !

**Comment by GuillaumeGomez** [comment]
It's fixed.

**Comment by GuillaumeGomez** [comment]
Still working on it ?

**Comment by gkoz** [comment]
Yeah, I had a cold so couldn't do much, going to pick it up now. I won't mind someone else doing the rest of the signals though haha

**Comment by GuillaumeGomez** [comment]
I'll have a busy week-end but why not next week ? Mail me to remind me it ! :-)

**Comment by gkoz** [comment]
This should be it.
I've omitted a few signals that aren't recommended to connect in applications. In the unlikely case that anyone needs to add them, there're plenty examples now. Other than that the old `signals.rs` functionality should be covered, so I'm going to prepare a patch that removes the old style signals.
More fresh eyes on this are welcome cause there's been a lot of copy-pasting.

**Comment by GuillaumeGomez** [comment]
Sorry but I'll only take a look at it tomorrow. However, thanks for your work, the little part I saw is very nice.

**Comment by GuillaumeGomez** [comment]
I just checked your code. Nothing to say, it's just excellent. Thanks a lot for your work !

**Comment by gkoz** [comment]
Thanks :)

**Comment by GuillaumeGomez** [comment]
Well, actually it's thanks to you but thanks for thanking me for thanking you haha.

**Comment by oakes** [comment]
I've been out of the loop for a bit but I've been spending some time today trying to rebase onto the latest changes. I can't get the new signals to work because I can't pass mutable references to Fn closures. My IDE works by passing a mutable reference to a "state" struct to all my callbacks. Should I fix this by wrapping it in a `Cell` perhaps, or am I overlooking a better solution?

**Comment by gkoz** [comment]
@oakes I'm pretty sure the closures can't be made `FnMut` because they need to be reentrant, so you'd have to use cells. Right now they're also `'static` i.e. can't capture any non-static references, so, you might also need `Rc`. The latter limitation could be overcome of it turned out to be a big issue.

**Comment by oakes** [comment]
I've managed to overhaul my code to use `Rc<RefCell>`. The only remaining problem is that it is panicing due to conflicting borrows. There's a code-path where I borrow the state from the `RefCell`, pass it to a function that refreshes my `TreeView`, which then triggers the "row_expanded" signal, which in turn borrows the state from the `RefCell`. I didn't consider this beforehand, but it means I can't borrow my state in any code that might trigger a signal that needs that state as well. I'll have to think about this more I suppose.

**Comment by gkoz** [comment]
This sounds like proof that allowing `FnMut`s would've been a disaster...
I wonder if you can partition the state into finer grained elements that could be borrowed in smaller scopes.

**Comment by oakes** [comment]
In this case I was able to avoid implementing a queue system, because I realized I don't actually need those signal handlers to run when I refresh the tree. I only need them to run when the user interacts with the tree. Therefore, I was able to fix it by not running the handlers if the tree is currently being refreshed. There may be side-effects I haven't considered yet, but so far it seems fine.

**Pull request merged**
