### PR TITLE
Set good version

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@gkoz: Is there any other version issue (outside of this file I mean) you're aware of ?

**Comment by gkoz** [comment]
Nope

:+1:

**Comment by gkoz** [comment]
Oh hey, I forgot I can merge now :)

**Comment by GuillaumeGomez** [comment]
Cool ! Merged.

**Comment by GuillaumeGomez** [comment]
Oh crap ! :( You want me to reopen it ? :p

**Pull request merged**
