### PR TITLE
Gate LevelBar cast on gtk_3_6

### PR DESCRIPTION
**Pull request by gkoz**
cc #83

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks ! Before I merge, is there any other missing ?

**Comment by gkoz** [comment]
According to https://github.com/rust-gnome/gtk/issues/83#issuecomment-103460902 this was the only problem as long as you make sure `gtk_3_6` isn't enabled.

**Comment by GuillaumeGomez** [comment]
I was speaking about other missing defined. ^^

**Comment by gkoz** [comment]
The recursive cargo features should be taking care of that, same as in the Rust sources. Were they not I wouldn't expect the builds to succeed.

**Comment by GuillaumeGomez** [comment]
Welll, we'll see if someone else finds something.

**Pull request merged**
