### PR TITLE
Old signals remnants cleanup

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I was sure they've already been removed from the code... A part of the old rgtk is gone :'(

**Comment by gkoz** [comment]
Macros are evil >:-0

**Comment by GuillaumeGomez** [comment]
Without macros, a big part of rust wouldn't exist ! So they're heaven !

**Comment by gkoz** [comment]
Yeah, that too. They're both then.

**Comment by GuillaumeGomez** [comment]
There's good and evil in everything (the wise man has spoke !).

**Pull request merged**
