### PR TITLE
Revert "Increase the refcount when wrapping a TreePath"

### LINKED ISSUE #54: TreeModel::get_path causes seg fault
To reproduce, simply add the following line in the first `for` loop of the [treeview example](https://github.com/rust-gnome/examples/blob/master/src/treeview.rs):

```rust
left_model.get_path(&iter);
```

Here's a more detailed error report from OS X:

```
Process:               treeview [39118]
Path:                  /Users/USER/Documents/*/treeview
Identifier:            treeview
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [38900]
Responsible:           iTerm [7452]
User ID:               502

Date/Time:             2015-05-02 16:03:07.463 -0400
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11
Anonymous UUID:        206A8CC9-7A2B-5AE7-BEE8-6335CC2349F3

Sleep/Wake UUID:       38864E3A-A942-43C3-B2BA-C2E751CCAC87

Time Awake Since Boot: 140000 seconds
Time Since Wake:       6500 seconds

Crashed Thread:        1  Dispatch queue: com.apple.libdispatch-manager

Exception Type:        EXC_CRASH (SIGSEGV)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Thread 0:: Dispatch queue: com.apple.main-thread
0   treeview                      	0x000000010d8518ca sys::stack_overflow::imp::signal_handler::h4e63d1ef5e5c6cc7m6u + 634
1   libsystem_platform.dylib      	0x00007fff950c6f1a _sigtramp + 26
2   ???                           	000000000000000000 0 + 0
3   libgobject-2.0.0.dylib        	0x000000010e209166 g_object_ref + 19
4   treeview                      	0x000000010d84170a widgets::tree_path::TreePath::wrap_pointer::h232b4229627a9490kRv + 74
5   treeview                      	0x000000010d84378c widgets::tree_model::TreeModel::get_path::h05678877dc449a007Vv + 204
6   treeview                      	0x000000010d83cdaa main::h5dab46603f9e8811Taa + 1562
7   treeview                      	0x000000010d853e89 rust_try_inner + 9
8   treeview                      	0x000000010d853e76 rust_try + 6
9   treeview                      	0x000000010d853621 rt::lang_start::h6bcbaed8391d369cpgw + 689
10  treeview                      	0x000000010d840ddf main + 79
11  libdyld.dylib                 	0x00007fff8865b5c9 start + 1
```

### PR DESCRIPTION
**Pull request by gkoz**
This should resolve #54

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks a lot !

**Comment by GuillaumeGomez** [comment]
Crap... I hoped it would solve my `treemodel` issue...

**Comment by gkoz** [comment]
You know the drill - we need a minimal test case and can debug from there :)

**Comment by GuillaumeGomez** [comment]
Well, we "just" need to find the minimal test case. :'(

**Pull request merged**
