### PR TITLE
Switch travis to container mode

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by gkoz** [comment]
Do I need another PR to see if it works?

**Comment by GuillaumeGomez** [comment]
No, I'll just restart #49.

**Comment by gkoz** [comment]
I guess that changeset had the old `.travis.yml` and it would need to be rebased to see the new one.

**Comment by GuillaumeGomez** [comment]
Hum... Hold on !

**Comment by gkoz** [comment]
It seems I broke something there, it doesn't seem schedule builds any more :(

**Comment by GuillaumeGomez** [comment]
Yup, that's weird. For now I'll revert your PR, we'll take anoter look at it tomorrow ! ^^

**Comment by gkoz** [comment]
I've found the problem with my edit.
The bigger issue is the gtk package they're giving me is 3.4.2 not even 3.6. They're almost equally old at this point so it might not make a big difference...

**Comment by GuillaumeGomez** [comment]
Hum... Well, for now let's keep the "old" way.

**Pull request merged**
